#!/usr/bin/env python3

import common
import io
import pexpect


def complexes(call, sequences, max_complex_size, permutations):

    result = None

    # spawn a subprocess for the provided call
    p = pexpect.spawn(call, encoding="ascii")

    # suppress echo
    p.setecho(False)

    # interact to provide its input
    p.expect("Enter number of different sequences")
    p.sendline(str(len(sequences)))
    for sequence in sequences:
        p.expect("Enter sequence")
        p.sendline(sequence)
    p.expect("Enter max complex size to completely enumerate")
    p.sendline(max_complex_size)
    for entry in range(len(sequences)):
        p.expect("Enter permutation")
        p.sendline(permutations[entry])

    # start log the subprocess' result
    log = io.StringIO()
    p.logfile = log
    p.expect("{") # starting of JSON string
    log.seek(0)

    # store the result
    result = log.read()
    result = result.replace("\x00", "").replace("\n", "").replace("\r", "")

    log.close()
    p.close()

    return (p.exitstatus, result)



if __name__ == "__main__":
    common.print_license()

    call = "complexes"
    sequences = [
        "GGCTGGTTTCTGCTCTCTAGTTCGCGAGGTGCAATCTCCTATC",
        "GTCTGGGATGCTGGATACTGAACCTAGAGAGCAGAAACCAGCC",
        "GTCTGGGATGCTGGATACTGAACCTAGAGAGCAGAAACCAGCC"
        ]
    max_complex_size = "1"
    permutations = {0: "1 2 3", 1: "1 2", 2: "1 3"}

    (status, result) = complexes(call, sequences, max_complex_size,
        permutations)

    print(status)
    print(result)

